micronaut:
  application:
    name: backend
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - ${ FRONTEND_URL:`http://localhost:5000` }
          allowed-headers:
            - Content-Type
            - Authorization
  security:
    authentication: bearer
    intercept-url-map:
      - pattern: /auth/**
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /auth/test
        httpMethod: GET
        access:
          - isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${ JWT_SECRET:`mySecretKey123456789012345678901234567890` }
        generator:
          access-token:
            expiration: 900 # 15 minutes
datasources:
  default:
    url: ${ JDBC_URL:`jdbc:h2:mem:testedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE` }
    driver-class-name: ${JDBC_DRIVER:org.h2.Driver}
    dialect: ${ JDBC_DIALECT:H2 }
    db-type: ${ JDBC_DB_TYPE:postgres }
    username: ${ JDBC_USERNAME:sa }
    password: ${ JDBC_PASSWORD:"" }
    schema-generate: CREATE_DROP
flyway:
  datasources:
    default:
      enabled: true
jpa:
  default:
    entity-scan:
      packages: mn_react.entities
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true